export const CITIES: Record<string, string[]> = {
 indian: [
 'Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Chennai', 'Kolkata', 'Pune', 'Ahmedabad',
 'Jaipur', 'Lucknow', 'Surat', 'Kanpur', 'Nagpur', 'Indore', 'Thane', 'Bhopal',
 'Visakhapatnam', 'Patna', 'Vadodara', 'Ghaziabad', 'Ludhiana', 'Agra', 'Nashik',
 'Faridabad', 'Meerut', 'Rajkot', 'Varanasi', 'Srinagar', 'Aurangabad', 'Dhanbad',
 'Amritsar', 'Allahabad', 'Ranchi', 'Howrah', 'Coimbatore', 'Jabalpur', 'Gwalior',
 'Vijayawada', 'Jodhpur', 'Madurai', 'Raipur', 'Kota', 'Chandigarh', 'Guwahati',
 'Solapur', 'Hubli', 'Tiruchirappalli', 'Bareilly', 'Mysore', 'Tiruppur', 'Gurgaon',
 'Aligarh', 'Jalandhar', 'Bhubaneswar', 'Salem', 'Warangal', 'Guntur', 'Bhiwandi',
 'Saharanpur', 'Gorakhpur', 'Bikaner', 'Amravati', 'Noida', 'Jamshedpur', 'Bhilai',
 'Cuttack', 'Firozabad', 'Kochi', 'Nellore', 'Bhavnagar', 'Dehradun', 'Durgapur',
 'Asansol', 'Rourkela', 'Nanded', 'Kolhapur', 'Ajmer', 'Akola', 'Gulbarga',
 'Jamnagar', 'Ujjain', 'Loni', 'Siliguri', 'Jhansi', 'Ulhasnagar', 'Jammu',
 'Sangli', 'Mangalore', 'Erode', 'Belgaum', 'Ambattur', 'Tirunelveli', 'Malegaon',
 'Gaya', 'Udaipur', 'Tirupati', 'Davanagere', 'Kozhikode', 'Mathura', 'Thanjavur',
 'Shimla', 'Pondicherry', 'Haridwar', 'Panipat', 'Karnal', 'Bathinda', 'Patiala',
 'Rohtak', 'Hisar', 'Sonipat', 'Bilaspur', 'Korba', 'Anantapur', 'Karimnagar',
 'Ramagundam', 'Nizamabad', 'Bellary', 'Tumkur', 'Bijapur', 'Shivamogga', 'Imphal',
 'Dibrugarh', 'Tezpur', 'Gangtok', 'Aizawl', 'Kohima', 'Itanagar', 'Agartala',
 'Silchar', 'Sambalpur', 'Berhampur', 'Kakinada', 'Ongole', 'Kurnool', 'Raichur',
 'Hassan', 'Mandya', 'Hospet', 'Bidar', 'Dharwad', 'Udupi', 'Chitradurga',
 'Ramanagara', 'Chikmagalur', 'Bagalkot', 'Haveri', 'Gadag', 'Koppal',
 'Thiruvalla', 'Palakkad', 'Thrissur', 'Alappuzha', 'Kollam', 'Kasaragod',
 'Malappuram', 'Kannur', 'Kottayam', 'Munnar', 'Wayanad', 'Idukki',
 'Thoothukudi', 'Dindigul', 'Sivakasi', 'Karur', 'Namakkal', 'Dharmapuri',
 'Krishnagiri', 'Pudukkottai', 'Ramanathapuram', 'Virudhunagar', 'Theni',
 'Ooty', 'Kodaikanal', 'Pollachi', 'Mettupalayam', 'Palani', 'Nagercoil',
 'Ratlam', 'Dewas', 'Sagar', 'Satna', 'Murwara', 'Singrauli', 'Burhanpur',
 'Kharagpur', 'Haldia', 'Bankura', 'Purulia', 'Baharampur', 'Medinipur',
 'Bolpur', 'Krishnanagar', 'Nabadwip', 'Shantiniketan', 'Kalyani',
 ],
 anglo: [
 'New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia',
 'San Antonio', 'San Diego', 'Dallas', 'San Jose', 'Austin', 'Jacksonville',
 'Fort Worth', 'Columbus', 'Charlotte', 'Indianapolis', 'San Francisco', 'Seattle',
 'Denver', 'Washington', 'Nashville', 'Oklahoma City', 'El Paso', 'Boston',
 'Portland', 'Las Vegas', 'Memphis', 'Louisville', 'Baltimore', 'Milwaukee',
 'Albuquerque', 'Tucson', 'Fresno', 'Sacramento', 'Mesa', 'Kansas City', 'Atlanta',
 'Omaha', 'Colorado Springs', 'Raleigh', 'Long Beach', 'Virginia Beach', 'Miami',
 'Oakland', 'Minneapolis', 'Tampa', 'Tulsa', 'Arlington', 'New Orleans', 'Cleveland',
 'Pittsburgh', 'Cincinnati', 'St. Louis', 'Detroit', 'Buffalo', 'Salt Lake City',
 'Honolulu', 'Anchorage', 'Richmond', 'Boise', 'Spokane', 'Boulder', 'Savannah',
 'Charleston', 'Asheville', 'Santa Fe', 'Annapolis', 'Madison', 'Des Moines',
 'Little Rock', 'Providence', 'Hartford', 'Reno', 'Chattanooga', 'Knoxville',
 'Durham', 'Lexington', 'Baton Rouge', 'Tacoma', 'Scottsdale', 'St. Petersburg',
 'Wichita', 'Bakersfield', 'Aurora', 'Riverside', 'Stockton', 'Corpus Christi',
 'Newark', 'Greensboro', 'Jersey City', 'Plano', 'Henderson', 'Lincoln',
 'London', 'Manchester', 'Birmingham', 'Leeds', 'Glasgow', 'Liverpool', 'Edinburgh',
 'Bristol', 'Sheffield', 'Cardiff', 'Belfast', 'Nottingham', 'Leicester', 'Newcastle',
 'Brighton', 'Oxford', 'Cambridge', 'Bath', 'York', 'Canterbury', 'Exeter',
 'Southampton', 'Plymouth', 'Norwich', 'Aberdeen', 'Dundee', 'Coventry', 'Swansea',
 'Derby', 'Reading', 'Wolverhampton', 'Stoke-on-Trent', 'Sunderland', 'Preston',
 'Toronto', 'Vancouver', 'Montreal', 'Calgary', 'Ottawa', 'Edmonton', 'Winnipeg',
 'Halifax', 'Victoria', 'Quebec City', 'Hamilton', 'Saskatoon', 'Regina', 'Kelowna',
 'Kingston', 'Kitchener', 'Barrie', 'Guelph', 'Thunder Bay', 'Sudbury', 'Oshawa',
 'Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Canberra', 'Hobart',
 'Darwin', 'Gold Coast', 'Wollongong', 'Geelong', 'Townsville', 'Cairns',
 'Toowoomba', 'Ballarat', 'Bendigo', 'Launceston', 'Mackay', 'Rockhampton',
 'Dublin', 'Cork', 'Galway', 'Limerick', 'Waterford', 'Kilkenny', 'Derry',
 'Sligo', 'Drogheda', 'Dundalk', 'Wexford', 'Athlone', 'Tralee', 'Ennis',
 'Topeka', 'Norfolk', 'Irvine', 'Hialeah', 'Garland', 'Fremont', 'Chesapeake',
 'Irving', 'Rochester', 'Oxnard', 'Akron', 'Dayton', 'Augusta', 'Montgomery',
 'Lubbock', 'Laredo', 'Chandler', 'Glendale', 'Tallahassee', 'Huntsville',
 'Worcester', 'Fayetteville', 'Cape Coral', 'Peoria', 'Sioux Falls',
 'Inverness', 'Stirling', 'Fort William', 'Paisley', 'Ayr', 'Dumfries', 'Oban',
 'Cheltenham', 'Stratford-upon-Avon', 'Winchester', 'Salisbury', 'Chester',
 'Colchester', 'Ipswich', 'Lancaster', 'Carlisle', 'Ripon', 'Harrogate',
 'Whitby', 'Scarborough', 'Folkestone', 'Margate', 'Deal', 'Hastings',
 'Fredericton', 'Charlottetown', 'Whitehorse', 'Yellowknife', 'Iqaluit',
 'Kamloops', 'Nanaimo', 'Prince George', 'Red Deer', 'Lethbridge', 'Brandon',
 'Moncton', 'Niagara Falls', 'Peterborough', 'Brantford', 'Sarnia', 'Chatham',
 ],
 european: [
 'Berlin', 'Paris', 'Rome', 'Madrid', 'Barcelona', 'Amsterdam', 'Vienna', 'Prague',
 'Brussels', 'Munich', 'Milan', 'Hamburg', 'Warsaw', 'Budapest', 'Zurich', 'Stockholm',
 'Copenhagen', 'Oslo', 'Helsinki', 'Lisbon', 'Athens', 'Bucharest', 'Sofia', 'Belgrade',
 'Zagreb', 'Ljubljana', 'Bratislava', 'Tallinn', 'Riga', 'Vilnius', 'Frankfurt',
 'Cologne', 'Stuttgart', 'Düsseldorf', 'Leipzig', 'Dresden', 'Nuremberg', 'Hanover',
 'Bremen', 'Dortmund', 'Essen', 'Bonn', 'Mannheim', 'Augsburg', 'Wiesbaden',
 'Marseille', 'Lyon', 'Toulouse', 'Nice', 'Bordeaux', 'Strasbourg', 'Nantes', 'Lille',
 'Montpellier', 'Rennes', 'Reims', 'Grenoble', 'Dijon', 'Angers', 'Rouen',
 'Naples', 'Turin', 'Florence', 'Bologna', 'Genoa', 'Venice', 'Palermo', 'Verona',
 'Catania', 'Bari', 'Trieste', 'Padua', 'Perugia', 'Siena', 'Pisa', 'Parma',
 'Valencia', 'Seville', 'Bilbao', 'Málaga', 'Zaragoza', 'Granada', 'Palma',
 'San Sebastián', 'Alicante', 'Córdoba', 'Valladolid', 'Vigo', 'Salamanca',
 'Rotterdam', 'The Hague', 'Utrecht', 'Eindhoven', 'Groningen', 'Leiden', 'Delft',
 'Gothenburg', 'Malmö', 'Uppsala', 'Linköping', 'Aarhus', 'Odense', 'Aalborg',
 'Bergen', 'Trondheim', 'Stavanger', 'Tampere', 'Turku', 'Espoo', 'Oulu',
 'Porto', 'Braga', 'Coimbra', 'Funchal', 'Faro', 'Thessaloniki', 'Heraklion', 'Patras',
 'Krakow', 'Wroclaw', 'Gdansk', 'Poznan', 'Lodz', 'Katowice', 'Lublin', 'Szczecin',
 'Brno', 'Ostrava', 'Plzen', 'Olomouc', 'Debrecen', 'Szeged', 'Pécs', 'Miskolc',
 'Graz', 'Salzburg', 'Innsbruck', 'Linz', 'Klagenfurt', 'Ghent', 'Antwerp', 'Bruges',
 'Liège', 'Namur', 'Basel', 'Geneva', 'Bern', 'Lausanne', 'Lucerne', 'Sankt Gallen',
 'Winterthur', 'Lugano', 'Biel', 'Thun', 'Vaduz', 'Monaco', 'San Marino',
 'Andorra la Vella', 'Luxembourg City', 'Reykjavik', 'Akureyri',
 'Rovaniemi', 'Joensuu', 'Kuopio', 'Jyväskylä', 'Vaasa', 'Lahti', 'Hämeenlinna',
 'Tromsø', 'Bodø', 'Ålesund', 'Kristiansand', 'Drammen', 'Fredrikstad',
 'Lund', 'Helsingborg', 'Norrköping', 'Örebro', 'Västerås', 'Umeå', 'Jönköping',
 'Cluj-Napoca', 'Timișoara', 'Iași', 'Constanța', 'Brașov', 'Craiova',
 'Varna', 'Plovdiv', 'Burgas', 'Stara Zagora', 'Ruse',
 'Niš', 'Novi Sad', 'Kragujevac', 'Subotica',
 'Split', 'Rijeka', 'Osijek', 'Zadar', 'Dubrovnik', 'Pula',
 'Maribor', 'Celje', 'Kranj', 'Koper',
 'Košice', 'Žilina', 'Prešov', 'Nitra', 'Banská Bystrica',
 'Tartu', 'Narva', 'Kaunas', 'Klaipėda', 'Šiauliai',
 'Daugavpils', 'Liepāja', 'Jelgava',
 ],
 east_asian: [
 'Tokyo', 'Seoul', 'Shanghai', 'Beijing', 'Singapore', 'Taipei', 'Hong Kong',
 'Osaka', 'Kyoto', 'Yokohama', 'Nagoya', 'Sapporo', 'Kobe', 'Fukuoka', 'Hiroshima',
 'Sendai', 'Kawasaki', 'Kitakyushu', 'Nara', 'Kanazawa', 'Nagasaki', 'Okinawa',
 'Kumamoto', 'Niigata', 'Hamamatsu', 'Shizuoka', 'Okayama', 'Matsuyama', 'Kagoshima',
 'Hakodate', 'Toyama', 'Matsumoto', 'Takayama', 'Kamakura', 'Nikko',
 'Busan', 'Incheon', 'Daegu', 'Daejeon', 'Gwangju', 'Ulsan', 'Suwon', 'Jeonju',
 'Cheongju', 'Changwon', 'Jeju', 'Pohang', 'Yongin', 'Seongnam', 'Goyang',
 'Gimhae', 'Chuncheon', 'Gyeongju', 'Andong', 'Sokcho', 'Gangneung', 'Iksan',
 'Guangzhou', 'Shenzhen', 'Chengdu', 'Hangzhou', 'Wuhan', 'Nanjing', 'Tianjin',
 'Chongqing', 'Xi\'an', 'Suzhou', 'Dongguan', 'Qingdao', 'Zhengzhou', 'Changsha',
 'Kunming', 'Dalian', 'Xiamen', 'Harbin', 'Fuzhou', 'Hefei', 'Ningbo', 'Jinan',
 'Shenyang', 'Wenzhou', 'Wuxi', 'Nanning', 'Guiyang', 'Lanzhou', 'Urumqi', 'Lhasa',
 'Hohhot', 'Taiyuan', 'Changchun', 'Nanchang', 'Haikou', 'Guilin', 'Lijiang',
 'Zhuhai', 'Foshan', 'Zhongshan', 'Yantai', 'Weifang', 'Luoyang', 'Xining',
 'Taichung', 'Kaohsiung', 'Tainan', 'Hsinchu', 'Taoyuan', 'Keelung', 'Chiayi',
 'Macau', 'Ulaanbaatar', 'Darkhan', 'Erdenet',
 'Naha', 'Otaru', 'Beppu', 'Saga', 'Asahikawa', 'Aomori', 'Akita',
 'Morioka', 'Yamagata', 'Fukushima', 'Mito', 'Utsunomiya', 'Maebashi',
 'Tottori', 'Shimane', 'Tokushima', 'Kochi', 'Oita', 'Miyazaki',
 'Yeosu', 'Tongyeong', 'Gimpo', 'Hwaseong', 'Paju', 'Asan', 'Gumi',
 'Jinju', 'Wonju', 'Cheonan', 'Sejong', 'Gunsan', 'Mokpo',
 'Baoding', 'Tangshan', 'Shijiazhuang', 'Nantong', 'Xuzhou', 'Changzhou',
 'Huzhou', 'Shaoxing', 'Jinhua', 'Taizhou', 'Zhangzhou', 'Putian',
 'Yichang', 'Xiangyang', 'Zhuzhou', 'Hengyang', 'Shantou', 'Jiangmen',
 'Zhaoqing', 'Huizhou', 'Meizhou', 'Liuzhou', 'Beihai', 'Yulin',
 ],
 latin: [
 'Mexico City', 'São Paulo', 'Buenos Aires', 'Bogotá', 'Lima', 'Santiago',
 'Rio de Janeiro', 'Guadalajara', 'Monterrey', 'Medellín', 'Cali', 'Brasília',
 'Salvador', 'Fortaleza', 'Belo Horizonte', 'Recife', 'Porto Alegre', 'Curitiba',
 'Manaus', 'Belém', 'Campinas', 'Santos', 'Florianópolis', 'Vitória',
 'Goiânia', 'Natal', 'São Luís', 'Maceió', 'João Pessoa', 'Teresina',
 'Campo Grande', 'Cuiabá', 'Aracaju', 'Londrina', 'Joinville', 'Juiz de Fora',
 'Uberlândia', 'Ribeirão Preto', 'Sorocaba', 'São José dos Campos',
 'Puebla', 'Tijuana', 'León', 'Cancún', 'Mérida', 'Querétaro', 'Toluca',
 'Oaxaca', 'Veracruz', 'Acapulco', 'Chihuahua', 'Morelia', 'Aguascalientes',
 'San Luis Potosí', 'Hermosillo', 'Saltillo', 'Culiacán', 'Mazatlán',
 'Durango', 'Tampico', 'Villahermosa', 'Tuxtla Gutiérrez', 'Campeche',
 'Pachuca', 'Zacatecas', 'Colima', 'Tepic', 'Guanajuato', 'Taxco',
 'Córdoba', 'Rosario', 'Mendoza', 'La Plata', 'Mar del Plata', 'Tucumán',
 'Santa Fe', 'Salta', 'Neuquén', 'Bahía Blanca', 'San Juan', 'Resistencia',
 'Corrientes', 'Posadas', 'San Rafael', 'Ushuaia', 'Bariloche', 'Rawson',
 'Barranquilla', 'Cartagena', 'Bucaramanga', 'Pereira', 'Santa Marta', 'Manizales',
 'Cúcuta', 'Ibagué', 'Villavicencio', 'Armenia', 'Pasto', 'Neiva', 'Popayán',
 'Arequipa', 'Trujillo', 'Cusco', 'Chiclayo', 'Piura', 'Huancayo', 'Iquitos',
 'Tacna', 'Cajamarca', 'Ayacucho', 'Puno', 'Juliaca', 'Huaraz',
 'Valparaíso', 'Concepción', 'Antofagasta', 'Viña del Mar', 'Temuco',
 'La Serena', 'Iquique', 'Punta Arenas', 'Puerto Montt', 'Talca', 'Rancagua',
 'Montevideo', 'Quito', 'Guayaquil', 'Cuenca', 'Asunción', 'La Paz', 'Cochabamba',
 'Santa Cruz de la Sierra', 'Sucre', 'Oruro', 'Havana', 'San José', 'Panama City',
 'Santo Domingo', 'Guatemala City', 'Tegucigalpa', 'Managua', 'San Salvador',
 'Port-au-Prince', 'Kingston', 'Bridgetown', 'Nassau',
 'Paramaribo', 'Georgetown', 'Cayenne', 'Belize City', 'Colón',
 'Santa Cruz', 'Tarija', 'Potosí', 'Trinidad', 'Tupiza',
 'Machala', 'Ambato', 'Loja', 'Riobamba', 'Esmeraldas', 'Manta',
 'Ciudad del Este', 'Encarnación', 'Pedro Juan Caballero',
 'Paysandú', 'Salto', 'Maldonado', 'Rivera', 'Melo',
 'Maracaibo', 'Valencia', 'Maracay', 'Barquisimeto', 'Ciudad Guayana',
 'Maturín', 'San Cristóbal', 'Ciudad Bolívar', 'Puerto La Cruz', 'Cumaná',
 'Santiago de Cuba', 'Camagüey', 'Holguín', 'Santa Clara', 'Guantánamo',
 'San Pedro Sula', 'La Ceiba', 'Choloma', 'Comayagua',
 'Estelí', 'Masaya', 'Chinandega', 'Matagalpa', 'Granada',
 'Santa Ana', 'San Miguel', 'Soyapango', 'Mejicanos',
 ],
 middle_eastern: [
 'Dubai', 'Istanbul', 'Cairo', 'Riyadh', 'Tehran', 'Doha', 'Abu Dhabi', 'Beirut',
 'Amman', 'Baghdad', 'Muscat', 'Kuwait City', 'Manama', 'Ankara', 'Izmir', 'Jeddah',
 'Mecca', 'Medina', 'Dammam', 'Tabuk', 'Abha', 'Taif', 'Khobar', 'Jizan', 'Hail',
 'Najran', 'Al Jubail', 'Yanbu', 'Buraydah', 'Sakaka', 'Al Kharj', 'Arar',
 'Sharjah', 'Ajman', 'Ras Al Khaimah', 'Fujairah', 'Al Ain', 'Umm Al Quwain',
 'Alexandria', 'Giza', 'Luxor', 'Aswan', 'Sharm El Sheikh', 'Hurghada', 'Port Said',
 'Suez', 'Mansoura', 'Tanta', 'Ismailia', 'Fayoum', 'Zagazig', 'Damanhur',
 'Minya', 'Asyut', 'Sohag', 'Qena', 'Beni Suef', 'Kafr El Sheikh', 'Damietta',
 'Isfahan', 'Shiraz', 'Mashhad', 'Tabriz', 'Karaj', 'Ahvaz', 'Kerman', 'Yazd',
 'Qom', 'Rasht', 'Hamadan', 'Kermanshah', 'Bandar Abbas', 'Arak', 'Zanjan',
 'Sanandaj', 'Gorgan', 'Birjand', 'Bushehr', 'Ilam',
 'Antalya', 'Bursa', 'Adana', 'Gaziantep', 'Konya', 'Mersin', 'Kayseri', 'Trabzon',
 'Eskisehir', 'Diyarbakir', 'Samsun', 'Denizli', 'Malatya', 'Erzurum', 'Van',
 'Basra', 'Erbil', 'Sulaymaniyah', 'Najaf', 'Karbala', 'Kirkuk', 'Mosul', 'Ramadi',
 'Aleppo', 'Damascus', 'Homs', 'Latakia', 'Tartus',
 'Tripoli', 'Casablanca', 'Rabat', 'Marrakech', 'Fez', 'Tangier', 'Agadir',
 'Meknes', 'Oujda', 'Kenitra', 'Tetouan',
 'Tunis', 'Algiers', 'Oran', 'Constantine', 'Annaba', 'Setif', 'Batna', 'Blida',
 'Sfax', 'Sousse', 'Kairouan', 'Bizerte', 'Gabès', 'Monastir',
 'Bejaia', 'Tlemcen', 'Djelfa', 'Sidi Bel Abbès', 'Biskra', 'Skikda',
 'Tizi Ouzou', 'Mostaganem', 'El Oued', 'Chlef', 'Médéa',
 'Benghazi', 'Misrata', 'Zliten', 'Zawiya', 'Sabratha',
 'Irbid', 'Zarqa', 'Aqaba', 'Madaba', 'Salt', 'Jerash',
 'Sidon', 'Byblos', 'Jounieh', 'Zahle', 'Baalbek',
 'Salalah', 'Nizwa', 'Sohar', 'Sur', 'Ibri',
 'Al Khor', 'Al Wakrah', 'Al Rayyan', 'Umm Salal', 'Madinat ash Shamal',
 ],
 african: [
 'Lagos', 'Nairobi', 'Johannesburg', 'Cape Town', 'Accra', 'Addis Ababa',
 'Dar es Salaam', 'Kinshasa', 'Luanda', 'Khartoum', 'Abuja', 'Durban', 'Pretoria',
 'Port Elizabeth', 'Kampala', 'Lusaka', 'Harare', 'Maputo', 'Dakar', 'Douala',
 'Yaoundé', 'Bamako', 'Conakry', 'Ouagadougou', 'Abidjan', 'Kumasi', 'Ibadan',
 'Kano', 'Port Harcourt', 'Kaduna', 'Benin City', 'Enugu', 'Onitsha', 'Warri',
 'Calabar', 'Abeokuta', 'Jos', 'Ilorin', 'Owerri', 'Uyo', 'Aba', 'Maiduguri',
 'Zaria', 'Sokoto', 'Minna', 'Akure', 'Osogbo', 'Bauchi', 'Lafia', 'Lokoja',
 'Mombasa', 'Kisumu', 'Nakuru', 'Eldoret', 'Meru', 'Nyeri', 'Thika', 'Malindi',
 'Lamu', 'Garissa', 'Machakos', 'Naivasha', 'Nanyuki', 'Kitale', 'Kakamega',
 'Zanzibar City', 'Arusha', 'Dodoma', 'Mwanza', 'Mbeya', 'Tanga', 'Morogoro',
 'Iringa', 'Tabora', 'Kigoma', 'Songea', 'Musoma', 'Bukoba',
 'Bloemfontein', 'East London', 'Pietermaritzburg', 'Nelspruit', 'Polokwane',
 'Kimberley', 'Rustenburg', 'Soweto', 'Stellenbosch', 'George', 'Knysna',
 'Paarl', 'Worcester', 'Upington', 'Vereeniging', 'Witbank',
 'Windhoek', 'Gaborone', 'Lilongwe', 'Blantyre', 'Bujumbura', 'Kigali', 'Mogadishu',
 'Djibouti', 'Antananarivo', 'Freetown', 'Monrovia', 'Lomé', 'Niamey',
 'N\'Djamena', 'Brazzaville', 'Libreville', 'Malabo', 'Bangui', 'Asmara', 'Juba',
 'Maseru', 'Mbabane', 'Praia', 'São Tomé', 'Moroni', 'Banjul', 'Bissau',
 'Touba', 'Thiès', 'Saint-Louis', 'Ziguinchor', 'Kaolack',
 'Tamale', 'Sekondi-Takoradi', 'Cape Coast', 'Koforidua', 'Sunyani',
 'Bobo-Dioulasso', 'Koudougou', 'Ouahigouya', 'Banfora',
 'Mopti', 'Ségou', 'Sikasso', 'Kayes', 'Koutiala',
 'Pointe-Noire', 'Dolisie', 'Nkayi', 'Owando',
 'Lubumbashi', 'Mbuji-Mayi', 'Kisangani', 'Kananga', 'Bukavu', 'Goma',
 'Huambo', 'Lobito', 'Benguela', 'Lubango', 'Cabinda', 'Malanje',
 'Toamasina', 'Antsirabe', 'Fianarantsoa', 'Mahajanga', 'Toliara',
 'Bulawayo', 'Chitungwiza', 'Mutare', 'Gweru', 'Masvingo',
 'Ndola', 'Kitwe', 'Kabwe', 'Chipata', 'Livingstone', 'Mufulira',
 ],
};

export const STREETS: Record<string, string[]> = {
 indian: [
 'MG Road', 'Linking Road', 'Park Street', 'Brigade Road', 'Commercial Street',
 'Anna Salai', 'Mount Road', 'Residency Road', 'Carter Road', 'Hill Road',
 'SV Road', 'LBS Marg', 'Western Express Highway', 'Eastern Express Highway',
 'Ring Road', 'Outer Ring Road', 'Old Madras Road', 'Hosur Road', 'Bannerghatta Road',
 'Sarjapur Road', 'Whitefield Main Road', 'Cunningham Road', 'Lavelle Road',
 'Infantry Road', 'Race Course Road', 'Necklace Road', 'Jubilee Hills Road',
 'Banjara Hills Road', 'Hitech City Road', 'Peddar Road', 'Colaba Causeway',
 'Marine Drive', 'FC Road', 'JM Road', 'Tilak Road', 'Law College Road',
 'Pali Hill Road', 'Juhu Tara Road', 'SG Highway', 'CG Road', 'Ashram Road',
 'Civil Lines Road', 'Mall Road', 'Rajpath', 'Janpath', 'Connaught Place',
 'Nehru Place', 'Karol Bagh Main Road', 'Chandni Chowk', 'Lajpat Nagar Main Road',
 'GT Road', 'Bellary Road', 'Kasturba Road', 'St Marks Road', 'Poonamallee High Road',
 'Cathedral Road', 'TTK Road', 'Boat Club Road', 'Dr Radhakrishnan Salai',
 'ECR Road', 'OMR Road', 'Velachery Main Road', 'Adyar Bridge Road',
 'GN Chetty Road', 'Mahatma Gandhi Road', 'Netaji Subhash Marg', 'Tilak Marg',
 'Mathura Road', 'Aurobindo Marg', 'Lodhi Road', 'Barakhamba Road',
 'Kasturba Gandhi Marg', 'Ashoka Road', 'Patel Road', 'Shankar Road',
 'Vivekananda Road', 'SP Mukherjee Road', 'AJC Bose Road', 'Chowringhee Road',
 'Gariahat Road', 'Rashbehari Avenue', 'EM Bypass', 'VIP Road',
 'Diamond Harbour Road', 'BT Road', 'Jessore Road', 'Rajarhat Road',
 'Salt Lake Bypass', 'Park Circus', 'Ballygunge Circular Road', 'APC Road',
 'JC Road', 'KH Road', 'Mysore Road', 'Magadi Road', 'Tumkur Road',
 'Hebbal Flyover', 'Marathahalli Road', 'HAL Airport Road', 'CMH Road',
 'Double Road', 'Sankey Road', 'Palace Road', 'Vittal Mallya Road',
 'Residency Road', 'Museum Road', 'Richmond Road', 'Langford Road',
 'Indiranagar 100 Feet Road', 'Koramangala Inner Ring Road',
 ],
 anglo: [
 'Broadway', 'Oxford Street', 'Fifth Avenue', 'Wall Street', 'Sunset Boulevard',
 'Hollywood Boulevard', 'Rodeo Drive', 'Pennsylvania Avenue', 'Michigan Avenue',
 'Madison Avenue', 'Park Avenue', 'Lexington Avenue', 'Main Street', 'Elm Street',
 'Maple Avenue', 'Oak Street', 'Cedar Lane', 'Pine Street', 'High Street',
 'King Street', 'Queen Street', 'Church Street', 'Market Street', 'Bridge Street',
 'Station Road', 'Victoria Street', 'George Street', 'Albert Road', 'Baker Street',
 'Regent Street', 'Bond Street', 'Fleet Street', 'Strand', 'Piccadilly',
 'Whitehall', 'Downing Street', 'Abbey Road', 'Kings Road', 'Portobello Road',
 'Carnaby Street', 'Brick Lane', 'Yonge Street', 'Bay Street', 'Bloor Street',
 'Robson Street', 'Granville Street', 'Pitt Street', 'Chapel Street',
 'Bourbon Street', 'Lombard Street', 'Castro Street', 'Haight Street',
 'Melrose Avenue', 'Beale Street', 'Canal Street', 'Peachtree Street',
 'Congress Avenue', 'Wilshire Boulevard', 'Mulholland Drive', 'Pacific Coast Highway',
 'Commonwealth Avenue', 'Newbury Street', 'Boylston Street', 'Lake Shore Drive',
 'Rush Street', 'State Street', 'River Walk', 'Royal Mile', 'Princes Street',
 'Buchanan Street', 'Deansgate', 'The Headrow', 'St Mary Street', 'Grafton Street',
 'Dame Street', 'Nassau Street', 'Flinders Street', 'Collins Street',
 'Bourke Street', 'Swanston Street', 'Pitt Street Mall', 'Elizabeth Street',
 'Spring Street', 'La Trobe Street', 'Exhibition Street', 'Lonsdale Street',
 'St Kilda Road', 'Brunswick Street', 'Smith Street',
 'Queen Street Mall', 'Adelaide Street', 'Edward Street', 'Ann Street',
 'Hay Street', 'Murray Street', 'St Georges Terrace', 'Beaufort Street',
 'King William Street', 'Rundle Street', 'Rundle Mall', 'Hindley Street',
 'North Terrace', 'Hutt Street', 'Grote Street', 'Currie Street',
 'O\'Connell Street', 'Henry Street', 'Talbot Street', 'Capel Street',
 'Baggot Street', 'Pearse Street', 'Harcourt Street', 'Dawson Street',
 'Dundas Street', 'Spadina Avenue', 'Queen Street West', 'King Street West',
 'St Clair Avenue', 'Danforth Avenue', 'College Street', 'Ossington Avenue',
 'Davie Street', 'Denman Street', 'Commercial Drive', 'Main Street',
 'Sainte-Catherine Street', 'Saint-Laurent Boulevard', 'Sherbrooke Street',
 ],
 european: [
 'Champs-Élysées', 'Via Condotti', 'La Rambla', 'Kurfürstendamm', 'Ringstrasse',
 'Bahnhofstrasse', 'Strøget', 'Kalverstraat', 'Gran Vía', 'Unter den Linden',
 'Friedrichstrasse', 'Alexanderplatz', 'Königsallee', 'Maximilianstrasse',
 'Rue de Rivoli', 'Boulevard Saint-Germain', 'Rue du Faubourg Saint-Honoré',
 'Avenue Montaigne', 'Boulevard Haussmann', 'Rue de la Paix',
 'Avenue des Champs-Élysées', 'Rue Saint-Honoré', 'Place Vendôme',
 'Via Veneto', 'Via del Corso', 'Via Montenapoleone', 'Via Toledo', 'Via Roma',
 'Via Tornabuoni', 'Via Dante', 'Corso Buenos Aires', 'Via Manzoni',
 'Passeig de Gràcia', 'Calle de Alcalá', 'Calle de Serrano', 'Puerta del Sol',
 'Calle Mayor', 'Paseo de la Castellana', 'Gran Via de les Corts Catalanes',
 'Damrak', 'Prinsengracht', 'Herengracht', 'Keizersgracht', 'Leidsestraat',
 'PC Hooftstraat', 'Rokin', 'Utrechtsestraat',
 'Mariahilfer Strasse', 'Graben', 'Kärntner Strasse', 'Kohlmarkt', 'Naschmarkt',
 'Wenceslas Square', 'Na Příkopě', 'Pařížská', 'Celetná',
 'Andrássy Avenue', 'Váci utca', 'Nowy Świat', 'Krakowskie Przedmieście',
 'Floriańska', 'Avenida da Liberdade', 'Rua Augusta', 'Rua do Carmo',
 'Drottninggatan', 'Kungsgatan', 'Strandvägen', 'Hamngatan',
 'Karl Johans gate', 'Esplanadi', 'Aleksanterinkatu', 'Pohjoisesplanadi',
 'Ermou Street', 'Tsimiski Street', 'Nevsky Prospect', 'Arbat Street',
 'Tverskaya Street', 'Knez Mihailova', 'Ilica', 'Čopova ulica',
 'Obchodná', 'Viru Street', 'Pilies Street', 'Brīvības iela',
 'Gedimino prospektas', 'Vokiečių gatvė', 'Nygade', 'Købmagergade',
 'Frederiksberggade', 'Søndergade', 'Midtbyen', 'Torgallmenningen',
 'Markveien', 'Grünerløkka', 'Mannerheimintie', 'Fredrikinkatu',
 'Iso Roobertinkatu', 'Västra Hamngatan', 'Vasagatan', 'Södra Larmgatan',
 'Corso Vittorio Emanuele', 'Via Etnea', 'Via Sparano', 'Via Chiaia',
 'Corso Garibaldi', 'Via Maqueda', 'Corso Italia', 'Via Indipendenza',
 'Calle de Fuencarral', 'Calle de Preciados', 'Calle del Arenal',
 'Rua de Santa Catarina', 'Rua das Flores', 'Rua Ferreira Borges',
 'Rue Neuve', 'Avenue Louise', 'Meir', 'Steenstraat',
 ],
 east_asian: [
 'Shibuya Crossing', 'Ginza', 'Omotesando', 'Takeshita Street', 'Nakamise Street',
 'Shinsaibashi', 'Dotonbori', 'Teramachi Street', 'Philosopher\'s Path', 'Harajuku',
 'Akihabara', 'Aoyama', 'Roppongi', 'Shinjuku', 'Kabukicho', 'Shimokitazawa',
 'Yanaka', 'Ameyoko', 'Kappabashi', 'Ninenzaka', 'Sannenzaka', 'Pontocho',
 'Gangnam-daero', 'Myeongdong', 'Insadong', 'Hongdae', 'Itaewon',
 'Bukchon Hanok Village', 'Sejong-daero', 'Yeouido', 'Apgujeong', 'Garosugil',
 'Samcheong-dong', 'Namdaemun', 'Dongdaemun', 'Jongno', 'Sinchon',
 'Nanjing Road', 'The Bund', 'Wangfujing', 'Chang\'an Avenue', 'Huaihai Road',
 'Zhongshan Road', 'Jiefang Road', 'Renmin Road', 'Chunxi Road', 'Beijing Road',
 'Jianghan Road', 'Zhongjie Street', 'Nanluoguxiang', 'Dashilan', 'Qianmen Street',
 'Orchard Road', 'Marina Bay', 'Bugis Street', 'Boat Quay', 'Clarke Quay',
 'Haji Lane', 'Arab Street', 'Serangoon Road', 'Kampong Glam', 'Little India',
 'Zhongxiao East Road', 'Xinyi Road', 'Ximending', 'Dihua Street',
 'Yongkang Street', 'Jiufen Old Street', 'Fengjia Night Market Road',
 'Nathan Road', 'Des Voeux Road', 'Queens Road', 'Hollywood Road', 'Temple Street',
 'Canton Road', 'Hennessy Road', 'Lockhart Road', 'Tsim Sha Tsui Promenade',
 'Ladder Street', 'Cat Street', 'Stanley Market Road', 'Tung Choi Street',
 'Peel Street', 'Staunton Street', 'Elgin Street', 'Gough Street',
 'Sai Yeung Choi Street', 'Fa Yuen Street', 'Shanghai Street',
 'Umeda', 'Tenjin', 'Sakae', 'Susukino', 'Tanukikoji', 'Nishiki Market',
 'Higashiyama', 'Arashiyama', 'Gion', 'Kiyomizu-zaka', 'Sanjo-dori',
 'Shijo-dori', 'Kawaramachi', 'Osu Shopping Street',
 'Ikseon-dong', 'Euljiro', 'Gwanghwamun', 'Mapo-daero', 'Teheran-ro',
 'Olympic-daero', 'Hangangno', 'Achasan-ro', 'Sinsa-dong',
 'Huangpi Road', 'Sichuan Road', 'Fumin Road', 'Yuyuan Road', 'Wukang Road',
 'Anfu Road', 'Julu Road', 'Changle Road', 'Fuxing Road', 'Yanan Road',
 ],
 latin: [
 'Avenida Paulista', 'Copacabana', 'Avenida Atlântica', 'Rua Oscar Freire',
 'Rua Augusta', 'Avenida Rio Branco', 'Avenida Presidente Vargas',
 'Rua das Laranjeiras', 'Rua Visconde de Pirajá', 'Avenida Nossa Senhora de Copacabana',
 'Avenida Vieira Souto', 'Rua Gonçalves Dias', 'Avenida Beira Mar',
 'Paseo de la Reforma', 'Avenida Insurgentes', 'Calle Madero', 'Avenida Juárez',
 'Avenida Chapultepec', 'Calle 5 de Mayo', 'Avenida Revolución',
 'Calzada de Tlalpan', 'Paseo de los Héroes', 'Avenida Hidalgo',
 'Avenida 9 de Julio', 'Avenida de Mayo', 'Calle Florida', 'Avenida Corrientes',
 'Avenida Santa Fe', 'Calle Defensa', 'Avenida Rivadavia', 'Calle Lavalle',
 'Avenida Callao', 'Caminito', 'Avenida Alvear', 'Avenida del Libertador',
 'Alameda', 'Avenida Providencia', 'Paseo Ahumada', 'Avenida Libertador',
 'Calle Larga', 'Avenida O\'Higgins', 'Avenida Apoquindo', 'Calle Monjitas',
 'Paseo Bulnes', 'Avenida Italia', 'Calle Lastarria',
 'Carrera Séptima', 'Calle 72', 'Avenida El Dorado', 'Avenida Caracas',
 'Carrera 15', 'Calle 85', 'Avenida Boyacá', 'Carrera 11',
 'Avenida Arequipa', 'Jirón de la Unión', 'Avenida Larco', 'Avenida Brasil',
 'Avenida Grau', 'Calle de las Pizzas', 'Avenida Salaverry', 'Avenida Javier Prado',
 'La Ronda', 'Avenida Amazonas', 'Calle García Moreno', 'Malecón Simón Bolívar',
 'Avenida 6 de Diciembre', 'Calle Juan León Mera',
 'Calle Obispo', 'Malecón', 'Avenida de los Presidentes', 'Calle 23',
 'Avenida Central', 'Paseo Colón', 'Rambla de Montevideo', 'Avenida 18 de Julio',
 'Paseo del Prado', 'Avenida Balboa', 'Calle Uruguay', 'Paseo de Montejo',
 'Calle Ocho', 'Avenida Constituyentes', 'Boulevard Kukulcán',
 'Avenida Tulum', 'Paseo de Montejo', 'Calle 60',
 'Rua XV de Novembro', 'Avenida Sete de Setembro', 'Rua Chile',
 'Avenida Beira-Mar', 'Rua da Praia', 'Avenida Ipiranga',
 'Rua dos Andradas', 'Avenida Protásio Alves', 'Avenida Borges de Medeiros',
 'Avenida Ernesto Geisel', 'Rua 14 de Julho', 'Avenida Mato Grosso',
 'Calle San Martín', 'Avenida Mitre', 'Calle Belgrano', 'Avenida Colón',
 'Paseo de los Leones', 'Avenida Constitución', 'Calle Independencia',
 ],
 middle_eastern: [
 'Sheikh Zayed Road', 'Jumeirah Beach Road', 'Al Maktoum Road', 'Khalifa Street',
 'Corniche Road', 'Hamdan Street', 'Electra Street', 'Airport Road',
 'Al Maryah Island', 'Saadiyat Island Road', 'Al Wasl Road', 'Al Khail Road',
 'King Fahd Road', 'Olaya Street', 'Tahlia Street', 'Prince Sultan Road',
 'King Abdullah Road', 'King Abdulaziz Road', 'Palestine Street', 'Medina Road',
 'Prince Mohammed Bin Abdulaziz Street', 'Sitteen Street', 'Khurais Road',
 'Istiklal Caddesi', 'Bagdat Caddesi', 'Atatürk Boulevard', 'Tunali Hilmi Caddesi',
 'Nispetiye Caddesi', 'Abdi Ipekci Caddesi', 'Cumhuriyet Caddesi', 'Valikonagi Caddesi',
 'Al Rashid Street', 'Sadoun Street', 'Abu Nuwas Street', 'Haifa Street',
 'Mutanabbi Street', 'Karrada Street', 'Mansour Street',
 'Kasr El Nil Street', 'Talaat Harb Street', 'Sharia el-Muizz', 'Corniche El Nil',
 'El Horreya Road', '26th of July Street', 'Salah Salem Road', 'Pyramids Road',
 'Al Ahram Street', 'Gameat El Dowal Street', 'Merghani Street',
 'Valiasr Street', 'Enghelab Street', 'Azadi Street', 'Taleghani Street',
 'Hafez Street', 'Ferdowsi Street', 'Chahar Bagh', 'Imam Reza Boulevard',
 'Keshavarz Boulevard', 'Motahari Street', 'Kargar Street', 'Vanak Street',
 'Pearl Roundabout', 'Exhibition Road', 'Al Waab Street', 'Lusail Boulevard',
 'Al Corniche', 'Souq Waqif Street', 'Al Sadd Street', 'Salwa Road',
 'Mohammed V Avenue', 'Hassan II Boulevard', 'Habib Bourguiba Avenue',
 'Al Khaleej Road', 'Sultan Qaboos Street', 'Al Qurum Road', 'Ruwi High Street',
 ],
  african: [
    'Victoria Island Road', 'Broad Street', 'Marina Street', 'Awolowo Road',
    'Allen Avenue', 'Adeola Odeku Street', 'Ozumba Mbadiwe Avenue', 'Ikorodu Road',
    'Herbert Macaulay Way', 'Ahmadu Bello Way', 'Tafawa Balewa Square',
    'Eko Atlantic Boulevard', 'Akin Adesola Street', 'Bourdillon Road',
    'Kingsway Road', 'Apapa Road', 'Adetokunbo Ademola Street', 'Ajose Adeogun Street',
    'Kenyatta Avenue', 'Moi Avenue', 'Uhuru Highway', 'Thika Road', 'Ngong Road',
    'Haile Selassie Avenue', 'Tom Mboya Street', 'Kimathi Street', 'Mama Ngina Street',
    'Waiyaki Way', 'Langata Road', 'Mombasa Road', 'Koinange Street',
    'Muindi Mbingu Street', 'Harambee Avenue', 'University Way', 'Luthuli Avenue',
    'Jan Smuts Avenue', 'Nelson Mandela Drive', 'Long Street', 'Adderley Street',
    'Vilakazi Street', 'Oxford Road', 'Rivonia Road', 'Sandton Drive',
    'William Nicol Drive', 'Commissioner Street', 'Bree Street', 'Kloof Street',
    'Loop Street', 'Strand Street', 'Wale Street', 'Shortmarket Street',
    'Independence Avenue', 'Liberation Road', 'Oxford Street', 'Ring Road Central',
    'Kwame Nkrumah Avenue', 'Castle Road', 'Cantonments Road', 'Spintex Road',
    'Osu Oxford Street', 'Labadi Road', 'Airport Residential Road',
    'Churchill Avenue', 'Bole Road', 'Meskel Square', 'Africa Avenue',
    'Ras Desta Damtew Road', 'Gambia Street', 'Guinea Conakry Street',
    'Entoto Road', 'Cameroon Street', 'Kenya Street',
    'Samora Avenue', 'Ali Hassan Mwinyi Road', 'Bagamoyo Road', 'Nyerere Road',
    'Nkrumah Street', 'Kivukoni Road', 'Sokoine Drive', 'Morogoro Road',
    'Nelson Mandela Road', 'New Bagamoyo Road', 'Old Dar es Salaam Road',
    'Lusaka Road', 'Cairo Road', 'Freedom Way', 'Katima Mulilo Road',
    'Independence Avenue', 'Robert Mugabe Avenue', 'Sam Nujoma Drive',
    'Werner List Street', 'Post Street Mall', 'Fidel Castro Street',
    'Kigali Boulevard', 'Avenue de la Paix', 'Boulevard de la Révolution',
    'Avenue du Commerce', 'Route de l\'Aéroport', 'Boulevard du 28 Novembre',
    'Avenue Patrice Lumumba', 'Boulevard Triomphal', 'Route Nationale 1',
  ],
};
