/**
 * 500+ real cities and 300+ real streets across 7 cultural regions.
 * Every entry is a real place that exists on a map.
 */

export const CITIES: Record<string, string[]> = {
  indian: [
    'Mumbai','Delhi','Bangalore','Hyderabad','Chennai','Kolkata','Pune','Ahmedabad',
    'Jaipur','Lucknow','Surat','Kanpur','Nagpur','Indore','Thane','Bhopal',
    'Visakhapatnam','Patna','Vadodara','Ghaziabad','Ludhiana','Agra','Nashik',
    'Faridabad','Meerut','Rajkot','Varanasi','Srinagar','Aurangabad','Dhanbad',
    'Amritsar','Navi Mumbai','Allahabad','Ranchi','Howrah','Coimbatore','Jabalpur',
    'Gwalior','Vijayawada','Jodhpur','Madurai','Raipur','Kochi','Chandigarh',
    'Mysore','Tiruchirappalli','Bhubaneswar','Salem','Warangal','Guntur','Bhiwandi',
    'Noida','Gurgaon','Mangalore','Thiruvananthapuram','Dehradun','Udaipur',
    'Tirupati','Shimla','Pondicherry','Goa','Gangtok','Shillong','Imphal',
    'Kohima','Aizawl','Itanagar','Agartala','Panaji','Daman','Silvassa',
    'Bokaro','Jamshedpur','Bhilai','Siliguri','Asansol','Durgapur','Kolhapur',
    'Ujjain','Sangli','Solapur','Hubli','Belgaum','Davangere','Bellary',
    'Gulbarga','Raichur','Bidar','Hospet','Tirunelveli','Nagercoil',
  ],
  anglo: [
    'New York','Los Angeles','Chicago','Houston','Phoenix','Philadelphia',
    'San Antonio','San Diego','Dallas','San Jose','Austin','Jacksonville',
    'Fort Worth','Columbus','Charlotte','Indianapolis','San Francisco','Seattle',
    'Denver','Washington DC','Nashville','Oklahoma City','El Paso','Boston',
    'Portland','Las Vegas','Memphis','Louisville','Baltimore','Milwaukee',
    'Albuquerque','Tucson','Fresno','Sacramento','Mesa','Kansas City',
    'Atlanta','Omaha','Colorado Springs','Raleigh','Long Beach','Virginia Beach',
    'Miami','Oakland','Minneapolis','Tampa','Tulsa','Arlington','New Orleans',
    'London','Manchester','Birmingham','Leeds','Glasgow','Liverpool','Edinburgh',
    'Bristol','Cardiff','Belfast','Sheffield','Nottingham','Leicester','Brighton',
    'Newcastle','Oxford','Cambridge','Bath','York','Exeter','Canterbury',
    'Toronto','Vancouver','Montreal','Calgary','Ottawa','Edmonton','Winnipeg',
    'Quebec City','Halifax','Victoria','Sydney','Melbourne','Brisbane','Perth',
    'Adelaide','Canberra','Hobart','Darwin','Gold Coast','Auckland','Wellington',
    'Dublin','Cork','Galway','Limerick','Boulder','Savannah','Charleston',
  ],
  european: [
    'Berlin','Hamburg','Munich','Frankfurt','Cologne','Stuttgart','Dusseldorf',
    'Leipzig','Dresden','Nuremberg','Hannover','Bremen','Paris','Lyon','Marseille',
    'Toulouse','Nice','Nantes','Strasbourg','Bordeaux','Lille','Montpellier',
    'Rome','Milan','Naples','Turin','Florence','Bologna','Venice','Genoa','Palermo',
    'Madrid','Barcelona','Valencia','Seville','Zaragoza','Malaga','Bilbao',
    'Amsterdam','Rotterdam','The Hague','Utrecht','Eindhoven','Stockholm',
    'Gothenburg','Malmo','Uppsala','Oslo','Bergen','Trondheim','Copenhagen',
    'Aarhus','Odense','Vienna','Graz','Salzburg','Innsbruck','Zurich','Geneva',
    'Basel','Bern','Lausanne','Prague','Brno','Warsaw','Krakow','Wroclaw',
    'Gdansk','Poznan','Budapest','Debrecen','Lisbon','Porto','Brussels',
    'Antwerp','Ghent','Helsinki','Tampere','Turku','Athens','Thessaloniki',
    'Bucharest','Sofia','Zagreb','Ljubljana','Bratislava','Tallinn','Riga','Vilnius',
  ],
  east_asian: [
    'Tokyo','Osaka','Yokohama','Nagoya','Sapporo','Kobe','Kyoto','Fukuoka',
    'Kawasaki','Hiroshima','Sendai','Kitakyushu','Chiba','Sakai','Niigata',
    'Hamamatsu','Shizuoka','Okayama','Kumamoto','Kagoshima','Seoul','Busan',
    'Incheon','Daegu','Daejeon','Gwangju','Suwon','Ulsan','Changwon','Goyang',
    'Seongnam','Bucheon','Shanghai','Beijing','Guangzhou','Shenzhen','Chengdu',
    'Wuhan','Hangzhou','Nanjing','Tianjin','Chongqing','Xian','Suzhou',
    'Harbin','Dalian','Qingdao','Zhengzhou','Changsha','Kunming','Fuzhou',
    'Xiamen','Ningbo','Dongguan','Foshan','Taipei','Kaohsiung','Taichung',
    'Tainan','Hong Kong','Singapore','Macau','Shenyang','Jinan','Hefei',
    'Nanchang','Guiyang','Lanzhou','Urumqi','Lhasa','Okinawa','Nara',
  ],
  latin: [
    'Mexico City','Guadalajara','Monterrey','Puebla','Tijuana','Leon',
    'Ciudad Juarez','Zapopan','Merida','Cancun','Queretaro','San Luis Potosi',
    'Aguascalientes','Hermosillo','Morelia','Chihuahua','Saltillo','Veracruz',
    'São Paulo','Rio de Janeiro','Brasilia','Salvador','Fortaleza','Belo Horizonte',
    'Manaus','Curitiba','Recife','Porto Alegre','Belem','Goiania','Guarulhos',
    'Campinas','Santos','Florianopolis','Vitoria','Buenos Aires','Cordoba',
    'Rosario','Mendoza','La Plata','Mar del Plata','Tucuman','Salta',
    'Bogota','Medellin','Cali','Barranquilla','Cartagena','Bucaramanga',
    'Lima','Arequipa','Trujillo','Cusco','Santiago','Valparaiso','Concepcion',
    'Montevideo','Quito','Guayaquil','Caracas','Maracaibo','Panama City',
    'San Jose','Havana','Santo Domingo','Guatemala City','Tegucigalpa','Managua',
    'San Salvador','Asuncion','La Paz','Santa Cruz',
  ],
  middle_eastern: [
    'Dubai','Abu Dhabi','Sharjah','Ajman','Riyadh','Jeddah','Mecca','Medina',
    'Dammam','Khobar','Tabuk','Abha','Cairo','Alexandria','Giza','Luxor',
    'Aswan','Sharm El Sheikh','Hurghada','Port Said','Istanbul','Ankara',
    'Izmir','Bursa','Antalya','Adana','Gaziantep','Konya','Mersin','Kayseri',
    'Tehran','Isfahan','Mashhad','Shiraz','Tabriz','Ahvaz','Kerman','Yazd',
    'Doha','Muscat','Kuwait City','Manama','Amman','Beirut','Baghdad',
    'Erbil','Basra','Damascus','Aleppo','Casablanca','Marrakech','Rabat',
    'Fes','Tangier','Algiers','Oran','Tunis','Sfax','Tripoli','Benghazi',
    'Sanaa','Aden','Ramallah','Tel Aviv','Jerusalem','Haifa','Nicosia',
    'Baku','Tbilisi','Yerevan',
  ],
  african: [
    'Lagos','Abuja','Port Harcourt','Kano','Ibadan','Kaduna','Benin City',
    'Enugu','Warri','Calabar','Owerri','Abeokuta','Ilorin','Jos','Maiduguri',
    'Nairobi','Mombasa','Kisumu','Nakuru','Eldoret','Thika','Malindi',
    'Johannesburg','Cape Town','Durban','Pretoria','Port Elizabeth','Bloemfontein',
    'East London','Pietermaritzburg','Soweto','Sandton','Accra','Kumasi',
    'Tamale','Tema','Sekondi-Takoradi','Cape Coast','Addis Ababa','Dire Dawa',
    'Mekelle','Gondar','Bahir Dar','Dar es Salaam','Dodoma','Arusha',
    'Mwanza','Zanzibar','Dakar','Saint-Louis','Thies','Kinshasa','Lubumbashi',
    'Mbuji-Mayi','Kampala','Jinja','Entebbe','Kigali','Butare','Lusaka',
    'Kitwe','Ndola','Harare','Bulawayo','Maputo','Luanda','Douala','Yaounde',
    'Bamako','Ouagadougou','Niamey','Conakry','Freetown','Monrovia','Lome',
    'Cotonou','Antananarivo','Windhoek','Gaborone','Lilongwe','Banjul',
  ],
};

export const STREETS: Record<string, string[]> = {
  indian: [
    'MG Road','Linking Road','FC Road','Law Garden Road','Brigade Road',
    'Park Street','Commercial Street','Residency Road','Cunningham Road',
    'Anna Salai','Mount Road','Nehru Place','Connaught Place','Rajpath',
    'Marine Drive','Juhu Beach Road','Bandra Bandstand','Carter Road',
    'Hill Road','SV Road','LBS Marg','Eastern Express Highway',
    'Outer Ring Road','Hosur Road','Bellary Road','Mysore Road',
    'Bannerghatta Road','Sarjapur Road','Whitefield Main Road',
    'Old Madras Road','Koramangala Inner Ring Road','Indiranagar Main Road',
    'Jayanagar 4th Block','JP Nagar Main Road','HSR Layout Sector 1',
    'Patel Nagar','Lajpat Nagar Main Market','Defence Colony',
    'Hauz Khas Village','Chandni Chowk','Karol Bagh','Rajouri Garden',
    'Malviya Nagar','Saket Main Road','Vasant Vihar','Greater Kailash',
  ],
  anglo: [
    'Broadway','Fifth Avenue','Wall Street','Madison Avenue','Park Avenue',
    'Sunset Boulevard','Hollywood Boulevard','Rodeo Drive','Melrose Avenue',
    'Michigan Avenue','State Street','Lakeshore Drive','Market Street',
    'Mission Street','Castro Street','Haight Street','Lombard Street',
    'Oxford Street','Regent Street','Bond Street','Fleet Street',
    'Piccadilly','Baker Street','Abbey Road','Carnaby Street',
    'Kings Road','Portobello Road','Brick Lane','Shoreditch High Street',
    'Kensington High Street','Fulham Road','Sloane Street',
    'Princes Street','Royal Mile','Sauchiehall Street',
    'Queen Street','King Street','Yonge Street','Bay Street',
    'Bloor Street','Dundas Street','Robson Street','Granville Street',
    'George Street','Pitt Street','Bourke Street','Collins Street',
    'Chapel Street','Flinders Street','Swanston Street','Grafton Street',
  ],
  european: [
    'Champs-Élysées','Rue de Rivoli','Boulevard Saint-Germain',
    'Rue du Faubourg Saint-Honoré','Avenue Montaigne','Rue de la Paix',
    'Kurfürstendamm','Unter den Linden','Friedrichstraße','Alexanderplatz',
    'Hauptstraße','Bahnhofstraße','Marienplatz','Maximilianstraße',
    'Via Condotti','Via del Corso','Via Montenapoleone','Via Roma',
    'Piazza Navona','Via Veneto','Gran Via','Paseo de la Castellana',
    'Las Ramblas','Passeig de Gracia','Calle Serrano','Calle Mayor',
    'Kalverstraat','Prinsengracht','Herengracht','Damrak',
    'Strandvägen','Drottninggatan','Kungsgatan','Sveavägen',
    'Strøget','Nyhavn','Karl Johans gate','Aker Brygge',
    'Ringstraße','Graben','Kärntner Straße','Mariahilfer Straße',
    'Bahnhofstrasse','Nowy Świat','Krakowskie Przedmiescie',
    'Váci utca','Andrássy út','Wenceslas Square','Na Příkopě',
  ],
  east_asian: [
    'Shibuya Crossing','Ginza Chuo-dori','Omotesando','Takeshita Street',
    'Nakamise-dori','Shinjuku-dori','Meiji-dori','Yasukuni-dori',
    'Dogenzaka','Koen-dori','Gangnam-daero','Apgujeong-ro',
    'Myeongdong-gil','Insadong-gil','Hongdae-ro','Itaewon-ro',
    'Jongno','Teheran-ro','Garosu-gil','Samcheong-dong-gil',
    'Nanjing Road','The Bund','Huaihai Road','Wangfujing Street',
    'Changan Avenue','Zhongshan Road','Jiefang Road','Renmin Road',
    'Orchard Road','Marina Bay','Raffles Place','Bugis Street',
    'Zhongxiao East Road','Xinyi Road','Dunhua South Road',
    'Nathan Road','Canton Road','Des Voeux Road','Queens Road',
    'Harajuku-dori','Aoyama-dori','Roppongi-dori','Ebisu-dori',
  ],
  latin: [
    'Paseo de la Reforma','Avenida Insurgentes','Calle Madero',
    'Avenida Juárez','Boulevard Miguel de Cervantes','Calle Cinco de Mayo',
    'Avenida Paulista','Rua Augusta','Rua Oscar Freire','Avenida Atlântica',
    'Rua XV de Novembro','Avenida Brigadeiro Faria Lima','Rua Direita',
    'Avenida 9 de Julio','Calle Florida','Avenida Corrientes',
    'Avenida de Mayo','Calle Defensa','Avenida Santa Fe',
    'Carrera Séptima','Calle 72','Avenida El Dorado','Calle 93',
    'Avenida Arequipa','Jirón de la Unión','Avenida Larco',
    'Avenida Providencia','Paseo Ahumada','Avenida Libertador',
    'Rambla de Montevideo','Avenida 18 de Julio','Calle Sarandí',
    'Malecón','Paseo del Prado','Calle Obispo','Avenida Central',
    'Boulevard de los Héroes','Calle Real','Avenida Bolívar',
    'Avenida Francisco de Miranda','Paseo Los Próceres',
  ],
  middle_eastern: [
    'Sheikh Zayed Road','Jumeirah Beach Road','Al Maktoum Road',
    'Al Khail Road','Khalifa Street','Corniche Road','Hamdan Street',
    'King Fahd Road','Olaya Street','Tahlia Street','King Abdullah Road',
    'Prince Sultan Street','Madinah Road','Al Haram Street',
    'Talaat Harb Street','Qasr El Nil Street','26th of July Street',
    'El Moez Street','Pyramids Road','Salah Salem Road','Nile Corniche',
    'Istiklal Caddesi','Bagdat Caddesi','Barbaros Bulvarı',
    'Ataturk Caddesi','Cumhuriyet Caddesi','Tunalı Hilmi Caddesi',
    'Valiasr Street','Enghelab Avenue','Ferdowsi Street',
    'Keshavarz Boulevard','Taleghani Avenue','Hafez Avenue',
    'Al Sadd Street','The Pearl Boulevard','Lusail Boulevard',
    'Al Qurum Street','Sultan Qaboos Street','Rainbow Street',
    'Hamra Street','Bliss Street','Rue Gouraud','Avenue Mohammed V',
    'Hassan II Avenue','Mohammed VI Boulevard',
  ],
  african: [
    'Victoria Island Road','Adeola Odeku Street','Ozumba Mbadiwe Avenue',
    'Allen Avenue','Awolowo Road','Herbert Macaulay Way',
    'Broad Street','Marina Street','Ikorodu Road','Lekki-Epe Expressway',
    'Kenyatta Avenue','Moi Avenue','Uhuru Highway','Haile Selassie Avenue',
    'Kimathi Street','Tom Mboya Street','Mama Ngina Street',
    'Nelson Mandela Drive','Jan Smuts Avenue','Oxford Road',
    'Vilakazi Street','Long Street','Adderley Street','Bree Street',
    'Commissioner Street','Sandton Drive','Rivonia Road',
    'Independence Avenue','Liberation Road','Oxford Street',
    'Kwame Nkrumah Avenue','Ring Road Central','Spintex Road',
    'Bole Road','Churchill Avenue','Meskel Square','Africa Avenue',
    'Ali Hassan Mwinyi Road','Samora Avenue','Ohio Street',
    'Boulevard de la République','Avenue Cheikh Anta Diop',
    'Route de lAéroport','Boulevard du 30 Juin','Avenue Patrice Lumumba',
  ],
};
