/**
 * JavaScript interface for the LocalMock WASM engine.
 *
 * Usage in a Worker:
 *   import { initWasm, wasmEngine } from '@localmock/wasm/js';
 *   await initWasm();
 *   const numbers = wasmEngine.generateIntegers(1000, 0, 100);
 */

// The WASM module types (generated by wasm-pack, manually declared here)
interface WasmExports {
  generate_integers(count: number, min: bigint, max: bigint, seed: bigint): Float64Array;
  generate_floats(count: number, min: number, max: number, precision: number, seed: bigint): Float64Array;
  generate_alphanumeric(count: number, length: number, seed: bigint): string;
  generate_hex(count: number, length: number, seed: bigint): string;
  generate_luhn(count: number, digits: number, seed: bigint): string;
  pick_random_indices(count: number, pool_size: number, seed: bigint): Uint32Array;
  generate_uuids(count: number, seed: bigint): string;
}

let wasm: WasmExports | null = null;
let seedCounter = Date.now();

function nextSeed(): bigint {
  return BigInt(++seedCounter);
}

/**
 * Initialize the WASM module. Must be called before using wasmEngine.
 * In a Worker context, call this once on startup.
 */
export async function initWasm(): Promise<void> {
  if (wasm) return;

  // Dynamic import of the wasm-pack generated module
  const mod = await import('../pkg/localmock_wasm.js');
  await mod.default(); // init() call that loads the .wasm file
  wasm = mod as unknown as WasmExports;
}

/**
 * Check if WASM engine is initialized and available.
 */
export function isWasmReady(): boolean {
  return wasm !== null;
}

/**
 * The WASM-accelerated generation engine.
 */
export const wasmEngine = {
  /**
   * Generate N random integers in [min, max] range.
   */
  generateIntegers(count: number, min: number, max: number): number[] {
    if (!wasm) throw new Error('WASM not initialized. Call initWasm() first.');
    const arr = wasm.generate_integers(count, BigInt(min), BigInt(max), nextSeed());
    return Array.from(arr);
  },

  /**
   * Generate N random floats in [min, max) with precision decimal places.
   */
  generateFloats(count: number, min: number, max: number, precision = 2): number[] {
    if (!wasm) throw new Error('WASM not initialized. Call initWasm() first.');
    const arr = wasm.generate_floats(count, min, max, precision, nextSeed());
    return Array.from(arr);
  },

  /**
   * Generate N random alphanumeric strings of given length.
   */
  generateAlphanumeric(count: number, length: number): string[] {
    if (!wasm) throw new Error('WASM not initialized. Call initWasm() first.');
    return wasm.generate_alphanumeric(count, length, nextSeed()).split('\n');
  },

  /**
   * Generate N hex strings of given length.
   */
  generateHex(count: number, length: number): string[] {
    if (!wasm) throw new Error('WASM not initialized. Call initWasm() first.');
    return wasm.generate_hex(count, length, nextSeed()).split('\n');
  },

  /**
   * Generate N Luhn-valid numbers with given digit count.
   */
  generateLuhn(count: number, digits: number): string[] {
    if (!wasm) throw new Error('WASM not initialized. Call initWasm() first.');
    return wasm.generate_luhn(count, digits, nextSeed()).split('\n');
  },

  /**
   * Pick N random indices from a pool (for selecting from arrays).
   */
  pickIndices(count: number, poolSize: number): number[] {
    if (!wasm) throw new Error('WASM not initialized. Call initWasm() first.');
    const arr = wasm.pick_random_indices(count, poolSize, nextSeed());
    return Array.from(arr);
  },

  /**
   * Generate N v4 UUIDs.
   */
  generateUuids(count: number): string[] {
    if (!wasm) throw new Error('WASM not initialized. Call initWasm() first.');
    return wasm.generate_uuids(count, nextSeed()).split('\n');
  },
};
